defmodule HelpdeskCommander.Repo.Migrations.RequireTaskEventActor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    INSERT INTO users (email, name, role)
    VALUES ('system@helpdesk.local', 'System', 'system')
    ON CONFLICT (email) DO NOTHING;
    """)

    execute("""
    UPDATE task_events
    SET actor_id = (SELECT id FROM users WHERE email = 'system@helpdesk.local')
    WHERE actor_id IS NULL;
    """)

    alter table(:task_events) do
      modify :actor_id, :bigint, null: false
    end
  end

  def down do
    alter table(:task_events) do
      modify :actor_id, :bigint, null: true
    end
  end
end
