defmodule HelpdeskCommander.Repo.Migrations.AddInquiries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inquiries, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :subject, :text, null: false
      add :body, :text, null: false
      add :source, :text, null: false, default: "web"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :requester_id,
          references(:users,
            column: :id,
            name: "inquiries_requester_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "inquiries_ticket_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:inquiries, "inquiries_requester_id_fkey")

    drop constraint(:inquiries, "inquiries_ticket_id_fkey")

    drop table(:inquiries)
  end
end
