defmodule HelpdeskCommander.Repo.Migrations.InitCoreResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :email, :text, null: false
      add :name, :text, null: false
      add :role, :text, null: false, default: "user"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tickets, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :public_id, :string, null: false, size: 32
      add :subject, :text, null: false
      add :description, :text
      add :type, :text, null: false, default: "question"
      add :status, :text, null: false, default: "new"
      add :priority, :text, null: false, default: "p3"
      add :impact, :text
      add :urgency, :text
      add :first_response_at, :utc_datetime_usec
      add :resolved_at, :utc_datetime_usec
      add :verified_at, :utc_datetime_usec
      add :closed_at, :utc_datetime_usec
      add :latest_message_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :requester_id,
          references(:users,
            column: :id,
            name: "tickets_requester_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :assignee_id,
          references(:users,
            column: :id,
            name: "tickets_assignee_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:tickets, [:public_id], name: "tickets_unique_public_id_index")

    create table(:tasks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :public_id, :string, null: false, size: 32
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "todo"
      add :priority, :text, null: false, default: "medium"
      add :due_date, :date
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assignee_id,
          references(:users,
            column: :id,
            name: "tasks_assignee_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:tasks, [:public_id], name: "tasks_unique_public_id_index")
  end

  def down do
    drop_if_exists unique_index(:tasks, [:public_id], name: "tasks_unique_public_id_index")

    drop constraint(:tasks, "tasks_assignee_id_fkey")

    drop table(:tasks)

    drop_if_exists unique_index(:tickets, [:public_id], name: "tickets_unique_public_id_index")

    drop constraint(:tickets, "tickets_requester_id_fkey")

    drop constraint(:tickets, "tickets_assignee_id_fkey")

    drop table(:tickets)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
