defmodule HelpdeskCommander.Repo.Migrations.AddProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:companies,
            column: :id,
            name: "products_company_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:products, [:company_id, :name],
             name: "products_unique_company_name_index"
           )

    alter table(:inquiries) do
      add :product_id, :bigint
    end

    alter table(:tickets) do
      add :product_id, :bigint
    end

    execute("""
    INSERT INTO products (company_id, name, description, inserted_at, updated_at)
    SELECT id, 'Default Product', '初期登録の製品', (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')
    FROM companies
    """)

    execute("""
    UPDATE tickets
    SET product_id = products.id
    FROM products
    WHERE tickets.company_id = products.company_id AND tickets.product_id IS NULL
    """)

    execute("""
    UPDATE inquiries
    SET product_id = products.id
    FROM products
    WHERE inquiries.company_id = products.company_id AND inquiries.product_id IS NULL
    """)

    alter table(:tickets) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "tickets_product_id_fkey",
               type: :bigint,
               prefix: "public"
             ),
             null: false
    end

    alter table(:inquiries) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "inquiries_product_id_fkey",
               type: :bigint,
               prefix: "public"
             ),
             null: false
    end
  end

  def down do
    drop constraint(:inquiries, "inquiries_product_id_fkey")

    alter table(:inquiries) do
      remove :product_id
    end

    drop_if_exists unique_index(:products, [:company_id, :name],
                     name: "products_unique_company_name_index"
                   )

    drop constraint(:products, "products_company_id_fkey")

    alter table(:products) do
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:tickets, "tickets_product_id_fkey")

    alter table(:tickets) do
      modify :product_id, :bigint
    end

    drop table(:products)

    alter table(:tickets) do
      remove :product_id
    end
  end
end
