defmodule HelpdeskCommander.Repo.Migrations.AddTicketMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticket_messages, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_messages_ticket_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :sender_id,
          references(:users,
            column: :id,
            name: "ticket_messages_sender_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:ticket_messages, "ticket_messages_ticket_id_fkey")

    drop constraint(:ticket_messages, "ticket_messages_sender_id_fkey")

    drop table(:ticket_messages)
  end
end
