defmodule HelpdeskCommander.Repo.Migrations.AddTicketLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticket_links, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :relation_type, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:companies,
            column: :id,
            name: "ticket_links_company_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_links_ticket_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :related_ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_links_related_ticket_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "ticket_links_created_by_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:ticket_links, [:ticket_id, :related_ticket_id, :relation_type],
             name: "ticket_links_unique_relation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ticket_links, [:ticket_id, :related_ticket_id, :relation_type],
                     name: "ticket_links_unique_relation_index"
                   )

    drop constraint(:ticket_links, "ticket_links_company_id_fkey")

    drop constraint(:ticket_links, "ticket_links_ticket_id_fkey")

    drop constraint(:ticket_links, "ticket_links_related_ticket_id_fkey")

    drop constraint(:ticket_links, "ticket_links_created_by_id_fkey")

    drop table(:ticket_links)
  end
end
