defmodule HelpdeskCommander.Repo.Migrations.AddTaskEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:task_events, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :event_type, :text, null: false
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "task_events_task_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "task_events_actor_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:task_events, "task_events_task_id_fkey")

    drop constraint(:task_events, "task_events_actor_id_fkey")

    drop table(:task_events)
  end
end
